### PR TITLE
First PR

### PR DESCRIPTION
**Pull request by iskandr**
Copied from PyEnsembl's `gtf_parsing` module, split into testable components, slightly generalized and added tests.

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/gtftools/1)

### CODE REVIEW

**Comment by iskandr** [comment]
Fixes https://github.com/hammerlab/pyensembl/issues/120

**Comment by tavinathanson** [comment]
Looks good overall. A few minor comments/questions. It doesn't really feel like a standalone library yet, since many comments refer to PyEnsembl. If we're going to stick to talking about Ensembl a lot, that should probably be confined to one area/class of the code.

Also, I didn't do a thorough job reviewing the actual parsing code (though I tried to scan it to some degree), partially because a lot of it looks mostly copy pasted. Let me know if there are any particular areas you think I should review. I also find GTF parsing hard to review in general since it's so (necessarily) messy/weird.

---

Reviewed 20 of 20 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[gtftools/line_parsing.py, line 109 \[r2\]](https://reviewable.io:443/reviews/hammerlab/gtftools/1#-Jzn821tr0qQ-B7Fw0B7)** ([raw file](https://github.com/hammerlab/gtftools/blob/5350d6c204423fc4fe43593da7c72511a5e01668/gtftools/line_parsing.py#L109)):</sup>
This seems oddly PyEnsembl-specific.

---

<sup>**[gtftools/read_gtf.py, line 132 \[r2\]](https://reviewable.io:443/reviews/hammerlab/gtftools/1#-Jzn6qjnZcGQeumo_aN4)** ([raw file](https://github.com/hammerlab/gtftools/blob/5350d6c204423fc4fe43593da7c72511a5e01668/gtftools/read_gtf.py#L132)):</sup>
Deleting columns while iterating over columns?

---

<sup>**[gtftools/required_columns.py, line 24 \[r1\]](https://reviewable.io:443/reviews/hammerlab/gtftools/1#-JzaIkS9Xs84eIqWrAFZ)** ([raw file](https://github.com/hammerlab/gtftools/blob/a23c5ec2567fdaa583d8fc539699be6e98abee34/gtftools/required_columns.py#L24)):</sup>
Maybe remove Ensembl-specific comments for parts that don't need to be Ensembl-specific? (Edit: this would be a pretty large change for another PR, but curious to get your thoughts)

---

<sup>**[gtftools/util.py, line 24 \[r1\]](https://reviewable.io:443/reviews/hammerlab/gtftools/1#-JzaJrCD1pB_RZJCzZec)** ([raw file](https://github.com/hammerlab/gtftools/blob/a23c5ec2567fdaa583d8fc539699be6e98abee34/gtftools/util.py#L24)):</sup>
Lame http://lists.apple.com/archives/darwin-kernel/2009/Mar/msg00005.html

---

<sup>**[README.md, line 3 \[r1\]](https://reviewable.io:443/reviews/hammerlab/gtftools/1#-JzaJuo0j4cBuNZ4LXKG)** ([raw file](https://github.com/hammerlab/gtftools/blob/a23c5ec2567fdaa583d8fc539699be6e98abee34/README.md#L3)):</sup>
`gtftools` feels like a weird name to me. `mhctools` makes sense, since it's a library that wraps "tools". If this is a parsing library that isn't wrapping any "tools", what about `gtfparse` or something like that?

---

<sup>**[test/test_parse_gtf_lines.py, line 8 \[r2\]](https://reviewable.io:443/reviews/hammerlab/gtftools/1#-Jzn7Oc5W0OqdCr7J8RP)** ([raw file](https://github.com/hammerlab/gtftools/blob/5350d6c204423fc4fe43593da7c72511a5e01668/test/test_parse_gtf_lines.py#L8)):</sup>
Load from a data file?

---

<sup>**[test/test_read_stringtie_gtf.py, line 5 \[r1\]](https://reviewable.io:443/reviews/hammerlab/gtftools/1#-JzaKPCHaPC_vOxeFZ8i)** ([raw file](https://github.com/hammerlab/gtftools/blob/a23c5ec2567fdaa583d8fc539699be6e98abee34/test/test_read_stringtie_gtf.py#L5)):</sup>
Can we throw in RefSeq GTF testing, since it should nominally work (and I have a test in PyEnsembl)?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/gtftools/1)

**Comment by iskandr** [comment]
Sadly, can't get to the Reviewable page (says browser can't reach github address).

**Comment by iskandr** [comment]
Review status: 5 of 24 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[gtfparse/line_parsing.py, line 109 \[r2\]](https://reviewable.io:443/reviews/hammerlab/gtfparse/1#-Jzn821tr0qQ-B7Fw0B7)** ([raw file](https://github.com/hammerlab/gtfparse/blob/5350d6c204423fc4fe43593da7c72511a5e01668/gtfparse/line_parsing.py#L109)):</sup>
I think this will come up as an issue for 

---

<sup>**[gtfparse/read_gtf.py, line 135 \[r2\]](https://reviewable.io:443/reviews/hammerlab/gtfparse/1#-Jzn6qjnZcGQeumo_aN4)** ([raw file](https://github.com/hammerlab/gtfparse/blob/5350d6c204423fc4fe43593da7c72511a5e01668/gtfparse/read_gtf.py#L135)):</sup>
Fixed

---

<sup>**[gtfparse/required_columns.py, line 26 \[r1\]](https://reviewable.io:443/reviews/hammerlab/gtfparse/1#-JzaIkS9Xs84eIqWrAFZ)** ([raw file](https://github.com/hammerlab/gtfparse/blob/a23c5ec2567fdaa583d8fc539699be6e98abee34/gtfparse/required_columns.py#L26)):</sup>
I think that would be a much larger change (since this library is still, in truth, very much crafted around the peculiarities of parsing Ensembl files)

---

<sup>**[gtfparse/util.py, line 25 \[r1\]](https://reviewable.io:443/reviews/hammerlab/gtfparse/1#-JzaJrCD1pB_RZJCzZec)** ([raw file](https://github.com/hammerlab/gtfparse/blob/a23c5ec2567fdaa583d8fc539699be6e98abee34/gtfparse/util.py#L25)):</sup>
Agreed!

---

<sup>**[README.md, line 3 \[r1\]](https://reviewable.io:443/reviews/hammerlab/gtfparse/1#-JzaJuo0j4cBuNZ4LXKG)** ([raw file](https://github.com/hammerlab/gtfparse/blob/a23c5ec2567fdaa583d8fc539699be6e98abee34/README.md#L3)):</sup>
Done (with all the Reviewable antics that followed)

---

<sup>**[test/test_parse_gtf_lines.py, line 8 \[r2\]](https://reviewable.io:443/reviews/hammerlab/gtfparse/1#-Jzn7Oc5W0OqdCr7J8RP)** ([raw file](https://github.com/hammerlab/gtfparse/blob/5350d6c204423fc4fe43593da7c72511a5e01668/test/test_parse_gtf_lines.py#L8)):</sup>
I like seeing the data in the test 

---

<sup>**[test/test_read_stringtie_gtf.py, line 5 \[r1\]](https://reviewable.io:443/reviews/hammerlab/gtfparse/1#-JzaKPCHaPC_vOxeFZ8i)** ([raw file](https://github.com/hammerlab/gtfparse/blob/a23c5ec2567fdaa583d8fc539699be6e98abee34/test/test_read_stringtie_gtf.py#L5)):</sup>
Done

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/gtfparse/1)

**Comment by tavinathanson** [comment]
Reviewed 9 of 23 files at r3, 10 of 10 files at r5.
Review status: 23 of 24 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

<sup>**[gtfparse/create_missing_features.py, line 64 \[r5\]](https://reviewable.io:443/reviews/hammerlab/gtfparse/1#-K-5IwKs5U7_Sl8oN1fu)** ([raw file](https://github.com/hammerlab/gtfparse/blob/a57d3ab81ae65ba4a383044b8c870eb3e7931f06/gtfparse/create_missing_features.py#L64)):</sup>
Not an error?

---

<sup>**[gtfparse/create_missing_features.py, line 73 \[r5\]](https://reviewable.io:443/reviews/hammerlab/gtfparse/1#-K-5JCI5R8PM-sRTt2QD)** ([raw file](https://github.com/hammerlab/gtfparse/blob/a57d3ab81ae65ba4a383044b8c870eb3e7931f06/gtfparse/create_missing_features.py#L73)):</sup>
Why an `OrderedDict`?

---

<sup>**[gtfparse/create_missing_features.py, line 77 \[r5\]](https://reviewable.io:443/reviews/hammerlab/gtfparse/1#-K-5HviqYrtMFGBJPKUx)** ([raw file](https://github.com/hammerlab/gtfparse/blob/a57d3ab81ae65ba4a383044b8c870eb3e7931f06/gtfparse/create_missing_features.py#L77)):</sup>
Extra newline

---

<sup>**[gtfparse/create_missing_features.py, line 79 \[r5\]](https://reviewable.io:443/reviews/hammerlab/gtfparse/1#-K-5Huj_0ozwPdzHqrbt)** ([raw file](https://github.com/hammerlab/gtfparse/blob/a57d3ab81ae65ba4a383044b8c870eb3e7931f06/gtfparse/create_missing_features.py#L79)):</sup>
typo: required

---

<sup>**[gtfparse/create_missing_features.py, line 109 \[r5\]](https://reviewable.io:443/reviews/hammerlab/gtfparse/1#-K-5JrhrpYfyrX13sYHa)** ([raw file](https://github.com/hammerlab/gtfparse/blob/a57d3ab81ae65ba4a383044b8c870eb3e7931f06/gtfparse/create_missing_features.py#L109)):</sup>
Typo: feature

---

<sup>**[gtfparse/create_missing_features.py, line 116 \[r5\]](https://reviewable.io:443/reviews/hammerlab/gtfparse/1#-K-5IIhzh0bLPJhglYkq)** ([raw file](https://github.com/hammerlab/gtfparse/blob/a57d3ab81ae65ba4a383044b8c870eb3e7931f06/gtfparse/create_missing_features.py#L116)):</sup>
Do you actually want to be printing here?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/gtfparse/1)

**Comment by tavinathanson** [comment]
Review status: 23 of 24 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/gtfparse/1)

**Comment by tavinathanson** [comment]
Review status: 23 of 24 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/gtfparse/1)

**Comment by iskandr** [comment]
Review status: 23 of 24 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[gtfparse/create_missing_features.py, line 64 \[r5\]](https://reviewable.io:443/reviews/hammerlab/gtfparse/1#-K-5IwKs5U7_Sl8oN1fu)** ([raw file](https://github.com/hammerlab/gtfparse/blob/a57d3ab81ae65ba4a383044b8c870eb3e7931f06/gtfparse/create_missing_features.py#L64)):</sup>
This is maybe illogical, originally this was a helper function for `read_gtf` which checked that these features are all actually missing. I'm going to change this to just an info log + `continue` since PyEnsembl calls this with all parsed DataFrames

---

<sup>**[gtfparse/create_missing_features.py, line 73 \[r5\]](https://reviewable.io:443/reviews/hammerlab/gtfparse/1#-K-5JCI5R8PM-sRTt2QD)** ([raw file](https://github.com/hammerlab/gtfparse/blob/a57d3ab81ae65ba4a383044b8c870eb3e7931f06/gtfparse/create_missing_features.py#L73)):</sup>
So that the DataFrame has columns in the same order as the GTF

---

<sup>**[gtfparse/create_missing_features.py, line 116 \[r5\]](https://reviewable.io:443/reviews/hammerlab/gtfparse/1#-K-5IIhzh0bLPJhglYkq)** ([raw file](https://github.com/hammerlab/gtfparse/blob/a57d3ab81ae65ba4a383044b8c870eb3e7931f06/gtfparse/create_missing_features.py#L116)):</sup>
Nope, thanks for catching that

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/gtfparse/1)

**Comment by tavinathanson** [comment]
Review status: 22 of 24 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[gtfparse/create_missing_features.py, line 64 \[r5\]](https://reviewable.io:443/reviews/hammerlab/gtfparse/1#-K-5IwKs5U7_Sl8oN1fu)** ([raw file](https://github.com/hammerlab/gtfparse/blob/a57d3ab81ae65ba4a383044b8c870eb3e7931f06/gtfparse/create_missing_features.py#L64)):</sup>
Ah, didn't realize it was always called

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/gtfparse/1)

**Pull request merged**
